import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { Plus, Sparkles, Wand2, Upload, LogOut } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { Story } from "@/types/story";
import { BottomNav } from "@/components/library/BottomNav";
import { AdminStoryCard } from "@/components/admin/AdminStoryCard";
import { StorySheet } from "@/components/admin/StorySheet";
import { deleteStoryFolder } from "@/lib/storage";
import { buildBentoSample } from "@/data/sampleBento";
import { BrandLogo } from "@/components/brand/BrandLogo";
import {
  MAX_STORY_JSON_BYTES,
  parseStoryJson,
} from "@/lib/generator/storyImport";

export const Route = createFileRoute("/admin/")({
  head: () => ({
    meta: [
      { title: "Continha ✦ Admin" },
      { name: "description", content: "Painel para criar e editar historinhas." },
    ],
  }),
  component: AdminPage,
});

function AdminPage() {
  const navigate = useNavigate();
  const [stories, setStories] = useState<Story[]>([]);
  const [loading, setLoading] = useState(true);
  const [sheetOpen, setSheetOpen] = useState(false);
  const [editing, setEditing] = useState<Story | null>(null);
  const briefFileInput = useRef<HTMLInputElement | null>(null);

  const handleStoryFile = async (file?: File) => {
    if (!file) return;
    try {
      if (file.size > MAX_STORY_JSON_BYTES) {
        throw new Error(
          `Arquivo muito grande (máx ${Math.round(MAX_STORY_JSON_BYTES / 1024)} KB).`,
        );
      }
      const text = await file.text();
      const { story, warnings } = parseStoryJson(text);
      warnings.forEach((w) => toast.info(w));
      setEditing(story);
      setSheetOpen(true);
      toast.success("✦ Historinha importada — revise e salve");
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Falha ao importar JSON";
      toast.error(msg);
    } finally {
      if (briefFileInput.current) briefFileInput.current.value = "";
    }
  };

  const load = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("stories")
      .select("*")
      .order("date", { ascending: false });
    setLoading(false);
    if (error) {
      toast.error("Erro ao carregar histórias");
      return;
    }
    setStories((data || []) as unknown as Story[]);
  };

  useEffect(() => {
    void load();
    // pick up a story generated by /admin/gerar
    try {
      const raw = sessionStorage.getItem("contame:pendingStory");
      if (raw) {
        sessionStorage.removeItem("contame:pendingStory");
        const story = JSON.parse(raw) as Story;
        setEditing(story);
        setSheetOpen(true);
        toast.info("Rascunho recuperado — salve para concluir");
      }
    } catch {
      /* noop */
    }
  }, []);

  const handleLogout = async () => {
    await supabase.auth.signOut();
    navigate({ to: "/auth" });
  };

  const handleDelete = async (s: Story) => {
    if (!window.confirm(`Excluir "${s.title}"? Esta ação não pode ser desfeita.`)) return;
    const { error } = await supabase.from("stories").delete().eq("id", s.id);
    if (error) {
      toast.error("Erro ao excluir");
      return;
    }
    void deleteStoryFolder(s.id);
    toast.success("🗑 História removida");
    void load();
  };

  return (
    <div className="min-h-dvh pb-24">
      <header className="safe-top mx-auto max-w-md px-5 pt-4 pb-3">
        <h1 className="sr-only">Painel Admin — Conte-me!</h1>
        <div className="flex items-center justify-between gap-3">
          <BrandLogo size="md" />
          <div className="flex items-center gap-2">
            <span className="inline-flex items-center rounded-full border border-amber/40 bg-secondary px-3 py-1 text-xs font-semibold tracking-wide text-foreground">
              Admin ✦
            </span>
            <button
              type="button"
              onClick={handleLogout}
              aria-label="Sair"
              title="Sair"
              className="flex h-8 w-8 items-center justify-center rounded-full text-muted-foreground transition hover:bg-muted hover:text-foreground"
            >
              <LogOut className="h-4 w-4" />
            </button>
          </div>
        </div>
        <p className="mt-2 text-xs text-muted-foreground">
          Crie, edite e organize suas historinhas.
        </p>
      </header>

      <main className="mx-auto max-w-md space-y-4 px-4">
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => {
              setEditing(null);
              setSheetOpen(true);
            }}
            className="inline-flex items-center gap-2 rounded-full bg-amber px-5 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm"
          >
            <Plus className="h-4 w-4" /> Nova Historinha
          </button>
          <button
            type="button"
            onClick={() => navigate({ to: "/admin/gerar" })}
            className="inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-amber to-amber/70 px-5 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm"
          >
            <Wand2 className="h-4 w-4" /> Gerar com IA
          </button>
          <button
            type="button"
            onClick={() => briefFileInput.current?.click()}
            title="Importar historinha completa a partir de um arquivo .json"
            className="inline-flex items-center gap-2 rounded-full border border-amber/40 bg-secondary px-5 py-2.5 text-sm font-semibold text-foreground"
          >
            <Upload className="h-4 w-4 text-amber" /> Importar historinha (JSON)
          </button>
          <input
            ref={briefFileInput}
            type="file"
            accept="application/json,.json"
            className="hidden"
            onChange={(e) => void handleStoryFile(e.target.files?.[0])}
          />
          <button
            type="button"
            onClick={() => {
              setEditing(buildBentoSample());
              setSheetOpen(true);
              toast.success("✦ Exemplo carregado — revise e salve");
            }}
            className="inline-flex items-center gap-2 rounded-full border border-amber/40 bg-secondary px-5 py-2.5 text-sm font-semibold text-foreground"
          >
            <Sparkles className="h-4 w-4 text-amber" /> Carregar exemplo: Bento
          </button>
        </div>

        <section className="space-y-2">
          <h2 className="font-display text-sm font-medium tracking-wide text-muted-foreground">
            Histórias publicadas
          </h2>
          {loading ? (
            <div className="space-y-2">
              {[0, 1].map((i) => (
                <div key={i} className="h-[68px] animate-pulse rounded-2xl bg-muted" />
              ))}
            </div>
          ) : stories.length === 0 ? (
            <p className="rounded-2xl border border-dashed border-border bg-card p-6 text-center text-sm text-muted-foreground">
              Nenhuma história ainda. Toque em "Nova Historinha".
            </p>
          ) : (
            <div className="space-y-2">
              {stories.map((s) => (
                <AdminStoryCard
                  key={s.id}
                  story={s}
                  onEdit={() => {
                    setEditing(s);
                    setSheetOpen(true);
                  }}
                  onDelete={() => handleDelete(s)}
                />
              ))}
            </div>
          )}
        </section>
      </main>

      <BottomNav active="admin" />

      <StorySheet
        open={sheetOpen}
        story={editing}
        onClose={() => setSheetOpen(false)}
        onSaved={() => void load()}
      />
    </div>
  );
}
