/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoMobileRouteImport } from './routes/diagnostico-mobile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminGerarRouteImport } from './routes/admin.gerar'
import { Route as ApiAdminGenerateImageRouteImport } from './routes/api/admin/generate-image'

const DiagnosticoMobileRoute = DiagnosticoMobileRouteImport.update({
  id: '/diagnostico-mobile',
  path: '/diagnostico-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGerarRoute = AdminGerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminGenerateImageRoute = ApiAdminGenerateImageRouteImport.update({
  id: '/api/admin/generate-image',
  path: '/api/admin/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostico-mobile': typeof DiagnosticoMobileRoute
  '/admin/gerar': typeof AdminGerarRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/generate-image': typeof ApiAdminGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico-mobile': typeof DiagnosticoMobileRoute
  '/admin/gerar': typeof AdminGerarRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/generate-image': typeof ApiAdminGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostico-mobile': typeof DiagnosticoMobileRoute
  '/admin/gerar': typeof AdminGerarRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/generate-image': typeof ApiAdminGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/diagnostico-mobile'
    | '/admin/gerar'
    | '/admin/'
    | '/api/admin/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnostico-mobile'
    | '/admin/gerar'
    | '/admin'
    | '/api/admin/generate-image'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/diagnostico-mobile'
    | '/admin/gerar'
    | '/admin/'
    | '/api/admin/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosticoMobileRoute: typeof DiagnosticoMobileRoute
  ApiAdminGenerateImageRoute: typeof ApiAdminGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico-mobile': {
      id: '/diagnostico-mobile'
      path: '/diagnostico-mobile'
      fullPath: '/diagnostico-mobile'
      preLoaderRoute: typeof DiagnosticoMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gerar': {
      id: '/admin/gerar'
      path: '/gerar'
      fullPath: '/admin/gerar'
      preLoaderRoute: typeof AdminGerarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/generate-image': {
      id: '/api/admin/generate-image'
      path: '/api/admin/generate-image'
      fullPath: '/api/admin/generate-image'
      preLoaderRoute: typeof ApiAdminGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGerarRoute: typeof AdminGerarRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGerarRoute: AdminGerarRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosticoMobileRoute: DiagnosticoMobileRoute,
  ApiAdminGenerateImageRoute: ApiAdminGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
